/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDemoTanstackQueryRouteImport } from './routes/_authenticated/demo/tanstack-query'
import { Route as AuthenticatedDemoStorybookRouteImport } from './routes/_authenticated/demo/storybook'
import { Route as AuthenticatedDemoStartServerFuncsRouteImport } from './routes/_authenticated/demo/start.server-funcs'
import { Route as AuthenticatedDemoStartApiRequestRouteImport } from './routes/_authenticated/demo/start.api-request'
import { Route as AuthenticatedDemoFormSimpleRouteImport } from './routes/_authenticated/demo/form.simple'
import { Route as AuthenticatedDemoFormNewPocRouteImport } from './routes/_authenticated/demo/form.new-poc'
import { Route as AuthenticatedDemoFormAddressRouteImport } from './routes/_authenticated/demo/form.address'
import { Route as AuthenticatedDemoApiTqTodosRouteImport } from './routes/_authenticated/demo/api.tq-todos'
import { Route as AuthenticatedDemoApiNamesRouteImport } from './routes/_authenticated/demo/api.names'
import { Route as AuthenticatedDemoStartSsrIndexRouteImport } from './routes/_authenticated/demo/start.ssr.index'
import { Route as AuthenticatedDemoStartSsrSpaModeRouteImport } from './routes/_authenticated/demo/start.ssr.spa-mode'
import { Route as AuthenticatedDemoStartSsrFullSsrRouteImport } from './routes/_authenticated/demo/start.ssr.full-ssr'
import { Route as AuthenticatedDemoStartSsrDataOnlyRouteImport } from './routes/_authenticated/demo/start.ssr.data-only'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoTanstackQueryRoute =
  AuthenticatedDemoTanstackQueryRouteImport.update({
    id: '/demo/tanstack-query',
    path: '/demo/tanstack-query',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStorybookRoute =
  AuthenticatedDemoStorybookRouteImport.update({
    id: '/demo/storybook',
    path: '/demo/storybook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartServerFuncsRoute =
  AuthenticatedDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartApiRequestRoute =
  AuthenticatedDemoStartApiRequestRouteImport.update({
    id: '/demo/start/api-request',
    path: '/demo/start/api-request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoFormSimpleRoute =
  AuthenticatedDemoFormSimpleRouteImport.update({
    id: '/demo/form/simple',
    path: '/demo/form/simple',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoFormNewPocRoute =
  AuthenticatedDemoFormNewPocRouteImport.update({
    id: '/demo/form/new-poc',
    path: '/demo/form/new-poc',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoFormAddressRoute =
  AuthenticatedDemoFormAddressRouteImport.update({
    id: '/demo/form/address',
    path: '/demo/form/address',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoApiTqTodosRoute =
  AuthenticatedDemoApiTqTodosRouteImport.update({
    id: '/demo/api/tq-todos',
    path: '/demo/api/tq-todos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoApiNamesRoute =
  AuthenticatedDemoApiNamesRouteImport.update({
    id: '/demo/api/names',
    path: '/demo/api/names',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartSsrIndexRoute =
  AuthenticatedDemoStartSsrIndexRouteImport.update({
    id: '/demo/start/ssr/',
    path: '/demo/start/ssr/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartSsrSpaModeRoute =
  AuthenticatedDemoStartSsrSpaModeRouteImport.update({
    id: '/demo/start/ssr/spa-mode',
    path: '/demo/start/ssr/spa-mode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartSsrFullSsrRoute =
  AuthenticatedDemoStartSsrFullSsrRouteImport.update({
    id: '/demo/start/ssr/full-ssr',
    path: '/demo/start/ssr/full-ssr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemoStartSsrDataOnlyRoute =
  AuthenticatedDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/demo/storybook': typeof AuthenticatedDemoStorybookRoute
  '/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/demo/api/tq-todos': typeof AuthenticatedDemoApiTqTodosRoute
  '/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
  '/demo/form/new-poc': typeof AuthenticatedDemoFormNewPocRoute
  '/demo/form/simple': typeof AuthenticatedDemoFormSimpleRoute
  '/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/demo/storybook': typeof AuthenticatedDemoStorybookRoute
  '/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/demo/api/tq-todos': typeof AuthenticatedDemoApiTqTodosRoute
  '/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
  '/demo/form/new-poc': typeof AuthenticatedDemoFormNewPocRoute
  '/demo/form/simple': typeof AuthenticatedDemoFormSimpleRoute
  '/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/demo/storybook': typeof AuthenticatedDemoStorybookRoute
  '/_authenticated/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/_authenticated/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/_authenticated/demo/api/tq-todos': typeof AuthenticatedDemoApiTqTodosRoute
  '/_authenticated/demo/form/address': typeof AuthenticatedDemoFormAddressRoute
  '/_authenticated/demo/form/new-poc': typeof AuthenticatedDemoFormNewPocRoute
  '/_authenticated/demo/form/simple': typeof AuthenticatedDemoFormSimpleRoute
  '/_authenticated/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/_authenticated/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/_authenticated/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/_authenticated/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/_authenticated/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/_authenticated/demo/start/ssr/': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/new-poc'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/demo/storybook'
    | '/demo/tanstack-query'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/new-poc'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/demo/storybook'
    | '/_authenticated/demo/tanstack-query'
    | '/_authenticated/demo/api/names'
    | '/_authenticated/demo/api/tq-todos'
    | '/_authenticated/demo/form/address'
    | '/_authenticated/demo/form/new-poc'
    | '/_authenticated/demo/form/simple'
    | '/_authenticated/demo/start/api-request'
    | '/_authenticated/demo/start/server-funcs'
    | '/_authenticated/demo/start/ssr/data-only'
    | '/_authenticated/demo/start/ssr/full-ssr'
    | '/_authenticated/demo/start/ssr/spa-mode'
    | '/_authenticated/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/tanstack-query': {
      id: '/_authenticated/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AuthenticatedDemoTanstackQueryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/storybook': {
      id: '/_authenticated/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof AuthenticatedDemoStorybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/server-funcs': {
      id: '/_authenticated/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof AuthenticatedDemoStartServerFuncsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/api-request': {
      id: '/_authenticated/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof AuthenticatedDemoStartApiRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/form/simple': {
      id: '/_authenticated/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof AuthenticatedDemoFormSimpleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/form/new-poc': {
      id: '/_authenticated/demo/form/new-poc'
      path: '/demo/form/new-poc'
      fullPath: '/demo/form/new-poc'
      preLoaderRoute: typeof AuthenticatedDemoFormNewPocRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/form/address': {
      id: '/_authenticated/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof AuthenticatedDemoFormAddressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/api/tq-todos': {
      id: '/_authenticated/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof AuthenticatedDemoApiTqTodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/api/names': {
      id: '/_authenticated/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof AuthenticatedDemoApiNamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/ssr/': {
      id: '/_authenticated/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/ssr/spa-mode': {
      id: '/_authenticated/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrSpaModeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/ssr/full-ssr': {
      id: '/_authenticated/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrFullSsrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo/start/ssr/data-only': {
      id: '/_authenticated/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoStorybookRoute: typeof AuthenticatedDemoStorybookRoute
  AuthenticatedDemoTanstackQueryRoute: typeof AuthenticatedDemoTanstackQueryRoute
  AuthenticatedDemoApiNamesRoute: typeof AuthenticatedDemoApiNamesRoute
  AuthenticatedDemoApiTqTodosRoute: typeof AuthenticatedDemoApiTqTodosRoute
  AuthenticatedDemoFormAddressRoute: typeof AuthenticatedDemoFormAddressRoute
  AuthenticatedDemoFormNewPocRoute: typeof AuthenticatedDemoFormNewPocRoute
  AuthenticatedDemoFormSimpleRoute: typeof AuthenticatedDemoFormSimpleRoute
  AuthenticatedDemoStartApiRequestRoute: typeof AuthenticatedDemoStartApiRequestRoute
  AuthenticatedDemoStartServerFuncsRoute: typeof AuthenticatedDemoStartServerFuncsRoute
  AuthenticatedDemoStartSsrDataOnlyRoute: typeof AuthenticatedDemoStartSsrDataOnlyRoute
  AuthenticatedDemoStartSsrFullSsrRoute: typeof AuthenticatedDemoStartSsrFullSsrRoute
  AuthenticatedDemoStartSsrSpaModeRoute: typeof AuthenticatedDemoStartSsrSpaModeRoute
  AuthenticatedDemoStartSsrIndexRoute: typeof AuthenticatedDemoStartSsrIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoStorybookRoute: AuthenticatedDemoStorybookRoute,
  AuthenticatedDemoTanstackQueryRoute: AuthenticatedDemoTanstackQueryRoute,
  AuthenticatedDemoApiNamesRoute: AuthenticatedDemoApiNamesRoute,
  AuthenticatedDemoApiTqTodosRoute: AuthenticatedDemoApiTqTodosRoute,
  AuthenticatedDemoFormAddressRoute: AuthenticatedDemoFormAddressRoute,
  AuthenticatedDemoFormNewPocRoute: AuthenticatedDemoFormNewPocRoute,
  AuthenticatedDemoFormSimpleRoute: AuthenticatedDemoFormSimpleRoute,
  AuthenticatedDemoStartApiRequestRoute: AuthenticatedDemoStartApiRequestRoute,
  AuthenticatedDemoStartServerFuncsRoute:
    AuthenticatedDemoStartServerFuncsRoute,
  AuthenticatedDemoStartSsrDataOnlyRoute:
    AuthenticatedDemoStartSsrDataOnlyRoute,
  AuthenticatedDemoStartSsrFullSsrRoute: AuthenticatedDemoStartSsrFullSsrRoute,
  AuthenticatedDemoStartSsrSpaModeRoute: AuthenticatedDemoStartSsrSpaModeRoute,
  AuthenticatedDemoStartSsrIndexRoute: AuthenticatedDemoStartSsrIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
